### PR TITLE
Unlock locked bindings before attempting to assign them

### LINKED ISSUE #30: depth not working? cannot change value of locked binding for '.onLoad'
I have a package (https://github.com/MichaelChirico/geohashTools) where several functions rely on Suggested packages.

At the top of such functions, I do a `requireNamespace(pkg)` check & error if the Suggested package isn't installed.

Earlier, I was doing coverage tests for these by (e.g. for function `foo`)

```
stub(foo, requireNamespace, FALSE)
testthat::expect_error(foo(x), 'please install')
```

There are enough functions like this now that I split off this test into a helper function (_unexported_):

```
check_suggested = function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("This function requires an installation of ", pkg,
         "; install.packages('", pkg, "') to proceed.")
  }
}
```

The old tests fail, I assume because the stubbing is only done _directly_ in the environment of `foo`, so when `foo` calls `check_suggested`, `requireNamespace` operates as normal.

So I tried to stub `check_suggested`:

```
stub(geohashTools:::check_suggested, requireNamespace, FALSE)
```

But this didn't work -- the code `foo(x)` runs without error.

Then I came across the `depth` argument which looked promising, but it's giving me a strange error:

```
stub(geohashTools:::check_suggested, 'requireNamespace', FALSE, depth = 2L)
```

> Error in assign(where_name, func, parent_env) : 
  cannot change value of locked binding for '.onLoad'

Am I using the argument wrong? How should I go about stubbing in this case to mock an environment where a suggested package is not installed?

### PR DESCRIPTION
**Pull request by sambrightman**
I'm creating this PR to fix #30 after not hearing any feedback
there. Hopefully if you are busy and this is an acceptable fix then it
will be easier to just merge something than keep up with issue
backlog.

### CODE REVIEW

**Comment by jimhester** [comment]
Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by sambrightman** [comment]
Added, let me know if there's anything else.

**Comment by jimhester** [comment]
Thanks! You are da bomb!

**Comment by sambrightman** [comment]
Anything I can do to help get a release out?

**Comment by nickolasjwilson** [comment]
Thanks for this fix, @sambrightman.

I, too, would like to see a new release having this fix.

**Pull request merged**
